/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Jul 19 2017
 * Processor: PIC16F877A
 * Compiler:  CCS for PIC
 */

#include <16F877A.h>
#FUSES NOWDT, HS, NOPUT, NOPROTECT, NODEBUG, NOBROWNOUT, NOLVP, NOCPD, NOWRT
#use delay(clock=20000000)


//lcear
#define LCD_CLEAR 0x01
//cursor home
#define LCD_CURSOR_HOME 0x02
//Entry mode set
#define LCD_ENTRY_MODE_SET 0x06//
//display control on/off
#define LCD_DISPLAY_ON_OFF_CONTROL 0x0F
//cursor or display shift
#define LCD_CURSOR_DISPLAY_SHIFT 0x14
//function set
#define LCD_FUNCTION_SET 0x38
//set CGRAM address


#bit RS =0x07.0
#bit RW =0x07.1
#bit EN =0x07.2

#bit LCD_D0=0x06.0
#bit LCD_D1=0x06.1
#bit LCD_D2=0x06.2
#bit LCD_D3=0x06.3
#bit LCD_D4=0x06.4
#bit LCD_D5=0x06.5
#bit LCD_D6=0x06.6
#bit LCD_D7=0x06.7

#byte LCD_DATA =0x06
#byte LCD_TRIS_DATA=0x86
#bit LCD_TRIS_D0=0x86.0
#bit LCD_TRIS_D1=0x86.1
#bit LCD_TRIS_D2=0x86.2
#bit LCD_TRIS_D3=0x86.3
#bit LCD_TRIS_D4=0x86.4
#bit LCD_TRIS_D5=0x86.5
#bit LCD_TRIS_D6=0x86.6
#bit LCD_TRIS_D7=0x86.7
#bit LCD_TRIS_RS=0x87.0
#bit LCD_TRIS_RW=0x87.1
#bit LCD_TRIS_EN=0x87.2




//
void lcd_wait(){
   delay_us(50);
}
void lcd_send_byte(char d){
   RW=0;
   EN=1;
   
   LCD_DATA=d;
   while(EN!=1);
   EN=0;
}

void lcd_cmd(int8 cmd){
   RS=0;
//!   RW=0;
//!   EN=1;
//!   
//!   LCD_DATA=cmd;
//!   while(EN!=1);
//!   EN=0;
   lcd_send_byte(cmd);
   
   lcd_wait();
}





void lcd_gotoXY(int8 y, int8 x){
   
   lcd_cmd(0x87);
   delay_ms(1);
}
void lcd_init(){
   
   //set tris
   LCD_TRIS_RS=0;
   LCD_TRIS_RW=0;
   LCD_TRIS_EN=0;
   LCD_TRIS_DATA=0x00;
   delay_ms(10);
   
   //cmd  
   lcd_cmd(LCD_FUNCTION_SET);
   delay_ms(10);
   lcd_cmd(LCD_CLEAR);
   delay_ms(10);
   lcd_cmd(LCD_DISPLAY_ON_OFF_CONTROL);
   delay_ms(10);
   lcd_cmd(LCD_ENTRY_MODE_SET);
   delay_ms(10);
}
void lcd_putc(int8 c){
   RS=1;
   RW=0;
   EN=1;
   LCD_DATA=c;
   while(!EN);
   EN=0;
   delay_us(500);
}
void lcd_getc(char c[]){
   int8 i=0;
   while(c[i]){
      lcd_putc(c[i]);
      i++;
   }
}
void lcd_puts(){}
void lcd_clr(){}


//
int main (void)
 { 

   lcd_init();
   lcd_putc('s');
   char str[20]="nhamsdfdxbfgnghmjb,kl,.lnj,.jk";
   lcd_cmd(0xC3);
   lcd_getc(str);
   //lcd_putc('s');
   //lcd_putc('s');
 
   while (1)
      ;
   return 0;
 }   

